version: '3.9'

services:
  api: &main_app
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
      target: prod
    image: titanic_examp:${TITANIC_EXAMP_VERSION:-latest}
    restart: always
    env_file:
      - .env
    environment:
      TITANIC_EXAMP_HOST: 0.0.0.0
      TITANIC_EXAMP_DB_FILE: /db_data/db.sqlite3
    volumes:
      - titanic_examp-db-data:/db_data/



volumes:
  titanic_examp-db-data:
    name: titanic_examp-db-data
